---
#  - name: load debian tasks
#  include_tasks: debian.yml
#  when:
#    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#  - name: load centos tasks
#  include_tasks: centos.yml
#  when:
#    - ansible_distribution == 'CentOS'

#  - name: load rhel tasks
#  include_tasks: rhel.yml
#  when:
#    - ansible_distribution = 'Red HatEnterprise Linux'

- name: adding nginx repo
  become: true
  become_user: root
  template:
    src: nginx.txt
    dest: /etc/yum.repos.d/nginx.repo

- name: update repos
  become: true
  become_user: root
  shell: yum repolist

- name: install nginx
  yum: name=nginx state=latest

- name: start nginx
  service:
    name: nginx
    state: started
